# Generated by Django 4.1.1 on 2022-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
